### ISSUE TITLE
Not Picking Gradient File

### ISSUE THREAD

**Issue by fahadmustafa650** [obiwanzenobi/gradient-borders#1]
Even after pub get and importing the library still this issue shows up
The method 'GradientBoxBorder' isn't defined for the type ClassName. Try correcting the name to the name of an existing method, or defining a method named 'GradientBoxBorder'.

**Comment by Adrian-Samoticha** [comment]
Did you import the widget correctly? Make sure the following import statement is included at the top of your file:

```dart
import 'package:gradient_borders/gradient_borders.dart';
```

**Comment by obiwanzenobi** [comment]
Closing for now.
Please make sure that you have correct imports, and/or you refreshed IDE after pub get.
